### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by AndMy** [JmStefanAndroid/EasyBehavior#1]
APP启动就闪退

06-28 15:28:20.256 6134-6134/me.stefan.easybehavior E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
06-28 15:28:20.309 6134-6134/me.stefan.easybehavior E/dalvikvm: VM aborting
06-28 15:28:20.309 6134-6134/me.stefan.easybehavior A/libc: Fatal signal 6 (SIGABRT) at 0x000017f6 (code=-6), thread 6134 (an.easybehavior)

**Comment by JmStefanAndroid** [comment]
你好，请详细说下你的机型版本?

**Comment by JmStefanAndroid** [comment]
bug已经解决了，放心使用吧😀
