### ISSUE TITLE
为什么布局里重叠了那么多NestedScrollView？

### ISSUE THREAD

**Issue by liaoinstan** [JmStefanAndroid/EasyBehavior#10]
不知道作者在demo1里大量使用了NestedScrollView是为何？并没有看出来布局有任何滚动特性

**Comment by JmStefanAndroid** [comment]
对啊，为什么要用那么多NestedScrollView呢？如果没有得到所需要要的滑动属性 ，请将[NestedScrollView](https://github.com/JmStefanAndroid/EasyBehavior/blob/master/app/src/main/java/me/stefan/easybehavior/widget/DisInterceptNestedScrollView.java)改为继承其他ViewGroup类，你能得到你想要的答案，这个类主要用于赋予其布局滚动的属性的同时，能够解决滑动冲突
