### ISSUE TITLE
当ViewPager中的Fragment放普通布局时无法上下滑动

### ISSUE THREAD

**Issue by WeiTaZhuang** [JmStefanAndroid/EasyBehavior#13]
当ViewPager中的Fragment放普通布局（如LinearLayout），在指示器父到顶时页面无法上下滑动，demo中是RecyclerView没出现该问题

**Comment by JmStefanAndroid** [comment]
Behavior行为是基于可滚动组件的，因此，可以在外层套一个NestedScrollview
