### ISSUE TITLE
Demo2中有个bug，当下滑刷新后，刷新即将完成时，轻轻上滑，就会出现刷新完成但是 SmileView(笑脸)没有隐藏的情况

### ISSUE THREAD

**Issue by fuyuguang** [JmStefanAndroid/EasyBehavior#14]
这种情况出现的概率还是比较大的，大神可以解决一下吗？
出现这个bug后，我再次下滑刷新（打断点）当刷新完成时，发现问题出在onStopNestedScroll 方法里的recovery方法。 该方法 的  第二行  代码  mFingerMoveDy 属性对应的值是终是 0.0 ， 也就是说第二行代码条件不成立，而
```
private void recovery(final AppBarLayout abl) {
        if (isRecovering) return;
        if (mFingerMoveDy > 0) {
             ...
        }else{
        // 应该是  else的情况你没作处理 ，导致的该bug吧 ？
        }

```

[对应的bug视频观看地址：](https://pan.baidu.com/s/14jsVMNZRZKqOsycIA2llVA)

**Comment by JmStefanAndroid** [comment]
demo2目前已弃用，可在backupv1中找到它，如有需要请提交pr
