### ISSUE TITLE
下拉的时候，TargetView会放大两次

### ISSUE THREAD

**Issue by Kunsan16** [JmStefanAndroid/EasyBehavior#18]
图片会放大两次，第二次放大比较大，然后还原，是什么原因找不出

**Comment by Kunsan16** [comment]
onStartNestedScroll
onNestedPreScroll
onNestedPreScroll
onNestedPreScroll
onNestedPreScroll
onNestedPreScroll
onStopNestedScroll     突然调用stop
onStartNestedScroll     然后再start
onNestedPreScroll
onNestedPreScroll
...
onStopNestedScroll

**Comment by Kunsan16** [comment]
发现我的design:26.1.0 所以这些回调onNested 方法都已经变了

**Comment by mastergyp** [comment]
试试 FixAppBarLayoutBehavior.java 我27.1.1可以
https://gist.github.com/chrisbanes/8391b5adb9ee42180893300850ed02f2#file-usage-java

**Comment by Kunsan16** [comment]
无法访问

**Comment by greadking** [comment]
@Kunsan16 com.android.support:design:27.1.1  兄弟问题解决了吗  我这也遇到了相同的问题

**Comment by JmStefanAndroid** [comment]
无法复现

**Comment by JmStefanAndroid** [comment]
有更多信息请再ReOpen
