### ISSUE TITLE
求指教

### ISSUE THREAD

**Issue by chendida** [JmStefanAndroid/EasyBehavior#2]
06-28 17:44:31.639 14638-14638/? E/dalvikvm: VM aborting
06-28 17:44:31.639 14638-14638/? A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 14638 (an.easybehavior)

**Comment by chendida** [comment]
克隆过来的项目，然后在AS中，死在了界面绘制这一步，即setContentView(R.layout.activity_main);没有执行完就挂掉了，现象是onCreate方法重复调用了三次

**Comment by JmStefanAndroid** [comment]
你好，我这里克隆下来能正常build，从你给的日志，我无法分析出你遇到的问题

**Comment by chendida** [comment]
非常感谢你提供的学习资源，我又重新克隆了一遍可以跑起来了。我分别用了5.0之前的手机和5.0之后的测了下，在屏幕适配这个地方还有点问题，就是5.0之前的的那张图还没有完全拉上去，留了一点空间。这里好像不能上图啊

**Comment by chendida** [comment]
还有一点，你这个项目的框架是两个模块吧，为什么要采用这种方式

**Comment by JmStefanAndroid** [comment]
我用4.4的模拟器测试，未发现适配问题，请提供下你所用的机型以及系统版本

**Comment by chendida** [comment]
手机型号: R7007,
                 SDK版本:18,
                 系统版本:4.3

**Comment by JmStefanAndroid** [comment]
你好，bug已修复，请update，感谢反馈
