### ISSUE TITLE
design 版本换成28.0.0 demo1不支持下拉放大

### ISSUE THREAD

**Issue by gexiangjie** [JmStefanAndroid/EasyBehavior#20]

**Comment by KeQian** [comment]
解决了吗

**Comment by JmStefanAndroid** [comment]
问题在于onStartNestedScroll onNestedPreScroll onStopNestedScroll 在28+过时了，更新了本地API后，效果恢复正常，代码已更新，下面是官方通知
![image](https://user-images.githubusercontent.com/15886002/75407829-ec008680-594e-11ea-9183-b901a50269f6.png)
