### ISSUE TITLE
沉浸式怎么处理

### ISSUE THREAD

**Issue by KotlinLan** [JmStefanAndroid/EasyBehavior#22]
你好，当图1往上滑动的时候，顶部的状态栏直接就是黑色的了，请问这个应该怎么修改？
![image](https://user-images.githubusercontent.com/50512101/66404432-a03a5880-ea12-11e9-97cd-9c84f2dc5415.png)
4.4以上可以实现沉浸式吗

**Comment by JmStefanAndroid** [comment]
状态栏部分的沉浸式使用了三方的工具com.jaeger.statusbarutil:library:1.4.0，上拉时demo里需要关闭沉浸式效果，就是这么设计的，如果你需要保持下拉状态的沉浸式，可以通过statusbarutil自行调整代码

**Comment by JmStefanAndroid** [comment]
如果有需要，请Reopen

**Comment by liosen** [comment]
沉浸式的朋友，解决方法：
注释两行代码
1.注释`initStatus();`
2.注释`initListener()`中的
`StatusBarUtil.setTranslucentForImageView(mActivity, (int) (255f * percent), null);`
======================具体原理，可以不看型===========================
我通过读源码看到有这么一个方法addTranslucentView，源码如下
`/**
     * 添加半透明矩形条
     *
     * @param activity       需要设置的 activity
     * @param statusBarAlpha 透明值
     */
    private static void addTranslucentView(Activity activity, @IntRange(from = 0, to = 255) int statusBarAlpha) {
ViewGroup contentView = (ViewGroup) activity.findViewById(android.R.id.content);
        View fakeTranslucentView = contentView.findViewById(FAKE_TRANSLUCENT_VIEW_ID);
        if (fakeTranslucentView != null) {
            if (fakeTranslucentView.getVisibility() == View.GONE) {
                fakeTranslucentView.setVisibility(View.VISIBLE);
            }
            fakeTranslucentView.setBackgroundColor(Color.argb(statusBarAlpha, 0, 0, 0));
        } else {
            contentView.addView(createTranslucentStatusBarView(activity, statusBarAlpha));
        }
    }`
然后，通过查找调用到这个方法的地方，发现在`initListener()`中有调用到。
运行后，发现toolbar不贴这顶部屏幕。
所以，再注释掉`initStatus();`即可（主要是要注释里面的`setLayoutParams`，但，注释`initStatus();`也可以）
然后再运行，发现完美适配沉浸式了。
结束
