### ISSUE TITLE
AndroidX 新的API上表现出bug

### ISSUE THREAD

**Issue by hjzlzh123** [JmStefanAndroid/EasyBehavior#23]
你好，AndroidX下拉放大图片的时候，马上放手然后快速惯性轻轻往上滑会出现，中间middle的布局网上滑动，但是viewpager content 的布局没有移动，最后导致中间留了很大的空白面积，请问有没有解决方法

**Comment by JmStefanAndroid** [comment]
你好，AndroidX尚未做兼容调试，后续，我会出一个针对AndroidX的调整

**Comment by hjzlzh123** [comment]
好的，谢谢

**Comment by VDshixiaoming** [comment]
你好，问下主要从哪方面去兼容，我也遇到类似的问题

**Comment by JmStefanAndroid** [comment]
不必在意上面的link，针对反馈的bug，我已经将androidx的适配版发布了，详情请查看androidx分支
