### ISSUE TITLE
下拉时是否可以下拉部件？

### ISSUE THREAD

**Issue by 1371030** [JmStefanAndroid/EasyBehavior#3]
下拉时是否可以下拉部件？拖动这个部件时才能把头部拉下来？

**Comment by JmStefanAndroid** [comment]
不太明白你的意思，所谓的部件是指一个按钮之类的么

**Comment by 1371030** [comment]
现在这个下拉时，随便什么位置便可进行下拉。如果指定了一个部件如tablayouut，在别的地方下拉不动，只能在这个tablayout上下拉才能起作用。
