### ISSUE TITLE
一些问题请教

### ISSUE THREAD

**Issue by vihuela** [JmStefanAndroid/EasyBehavior#5]
首先感谢提供这么好的demo学习
①AppBarLayoutOverScrollViewBehavior中，这里的mLastBottom获取逻辑不是很懂[AppBarLayoutOverScrollViewBehavior的129行](https://github.com/JmStefanAndroid/EasyBehavior/blob/master/app/src/main/java/me/stefan/easybehavior/demo1/behavior/AppBarLayoutOverScrollViewBehavior.java#L129)
②关于onStartNestedScroll回调时机的问题，一次滑动为什么会回调两次？
③DisInterceptNestedScrollView是否一定要集成NestedScrollView?

**Comment by JmStefanAndroid** [comment]
mLastBottom 用于控制下边界也就是AppBarLayout的bottom的位置，DisInterceptNestedScrollView主要用于屏蔽父类对子类事件的拦截，至于继承NestedScrollView，是想使用其嵌套滚动的属性,如果改为继承ScrollView则不行了

**Comment by vihuela** [comment]
可以，还有第二个问题啊

**Comment by JmStefanAndroid** [comment]
回调两次我不太清楚，麻烦你自己去查阅一下源码吧
