### ISSUE TITLE
Demo1下拉放大效果并不是每次都能成功

### ISSUE THREAD

**Issue by cat1024** [JmStefanAndroid/EasyBehavior#6]

**Comment by cat1024** [comment]
下拉操作有时能放缩，有时不能放缩

**Comment by JmStefanAndroid** [comment]
是对同一个位置的下拉操作吗？请说明下是哪个位置的下拉

**Comment by cat1024** [comment]
是对DisInterceptNestedScrollView部分进行的下拉操作。。。这个问题应该是比较常现的。。我试了几个手机都有这种情况，然后我修改了DisInterceptNestedScrollView 中
 private void doRequstDisallow(MotionEvent ev) {
        if (ev.getRawY() >= downY) {
            requestDisallowInterceptTouchEvent(true);
        } else {
            requestDisallowInterceptTouchEvent(false);
        }
    }
这个方法，加了个等于。。。就没有这种问题了@

**Comment by JmStefanAndroid** [comment]
这个是增加第二个demo用到的逻辑，第一个不需要这个逻辑，感谢反馈，我会尽快修正
