### ISSUE TITLE
把layout_func_in_uc.xml这个布局隐藏了之后下拉layout_uc_head_middle 这个布局会不见

### ISSUE THREAD

**Issue by ljackChen001** [JmStefanAndroid/EasyBehavior#7]
把layout_func_in_uc.xml这个布局隐藏了之后下拉layout_uc_head_middle 这个布局会不见

**Comment by JmStefanAndroid** [comment]
你好，请更新到最新的代码，再测试下，我这边用最新版本测试隐藏（无论是直接删除layout_func_in_uc还是INVISIBLE ,GONE）均未出现问题

**Comment by ljackChen001** [comment]
![2](https://user-images.githubusercontent.com/13534229/28397819-9a1173ae-6d36-11e7-8747-2a08a5a7d54a.jpg)
![1](https://user-images.githubusercontent.com/13534229/28397820-9b752358-6d36-11e7-8bb1-347f8d3bd3af.jpg)
你好，这是我这边用最新的demo跑的 下拉到一定的高度之后，就会变成空白，然后往上收缩一点就显示了

**Comment by ljackChen001** [comment]
我这边把layout_uc_head_middle  中的RelativeLayout 添加paddingTop15  paddingBottom20 就正常了
paddingTop+paddingBottom =35 就不会出现空白，当我设置paddingTop15  paddingBottom15 也会出现空白，

**Comment by JmStefanAndroid** [comment]
我不太明白你在哪个RelativeLayout加了padding，源码直接使用会导致这个空白吗

**Comment by ljackChen001** [comment]
恩 ， 源码直接就空白了 你加我QQ吧 我加你了的505951628

**Comment by JmStefanAndroid** [comment]
的确在删除了该布局会过度下拉会出现问题，我会尽快处理

**Comment by ljackChen001** [comment]
NestedScrollView 嵌套 RecyclerView之后上拉加载也是个问题，还没找到合适的解决办法，就类似于把你的Demo1和Demo2合并  ，NestedScrollView 嵌套 RecyclerView之后 上拉加载更多会被无限调用

**Comment by JmStefanAndroid** [comment]
标题所诉问题已经解决了，我不太清楚你所说的Q2，因为demo中，NestedScrollView中就嵌套了一个viewpager，viewpager中又嵌套了多个recyclerview，使用是正常的，这样吧，你在新的问题重新详细描述下，我将这个Q1关闭，方便别人来查找和解决问题
